### PR TITLE
Fix port

### PR DESCRIPTION
**Pull request by fd00**
Fix port

### CODE REVIEW

**Comment by phuonghuynh** [comment]
@findify Could we merge this ?

**Comment by diversit** [comment]
My pull-request (https://github.com/findify/sqsmock/pull/8) also contains this fix.

**Comment by alanroche** [comment]
Any chance this could be merged please?

**Comment by hebertsouza87** [comment]
@findify plese merge this

**Comment by Vostan** [comment]
WOW, such a hard decision to marge this

**Pull request merged**
